services:
  rabbitmq:
    image: "rabbitmq:3"
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
    restart: unless-stopped

    email-worker:
      build:
        context: mailer
        dockerfile: Dockerfile
        target: develop
      container_name: "email-worker"
      hostname: "email-worker"
      environment:
        RABBITMQ_HOST: "rabbitmq"
        RABBITMQ_PORT: "5672"
        RABBITMQ_USERNAME: "user"
        RABBITMQ_PASSWORD: "password"
        RECIPIENTS: ""
        SMTP_SERVER: ""
        SMTP_PORT: ""
        SMTP_USERNAME: ""
        SMTP_PASSWORD: ""
      depends_on:
        - rabbitmq
      restart: unless-stopped